// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZ8kPJ8VcGUkJhEkr5iFAjoePNlaQv8E',
    appId: '1:172786211960:web:cde7b4479f7c6eedd3618d',
    messagingSenderId: '172786211960',
    projectId: 'flutter-pokedex-b1b6c',
    authDomain: 'flutter-pokedex-b1b6c.firebaseapp.com',
    storageBucket: 'flutter-pokedex-b1b6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQiIiDl6-8-js6Sq1GHEZolcj7JnDGemE',
    appId: '1:172786211960:android:ba20c4fe5a7d91a6d3618d',
    messagingSenderId: '172786211960',
    projectId: 'flutter-pokedex-b1b6c',
    storageBucket: 'flutter-pokedex-b1b6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjSFZ5yp9K-vHOmsFKZ-SwJrYMJD70e3U',
    appId: '1:172786211960:ios:45687f8d8cd54d7fd3618d',
    messagingSenderId: '172786211960',
    projectId: 'flutter-pokedex-b1b6c',
    storageBucket: 'flutter-pokedex-b1b6c.firebasestorage.app',
    iosBundleId: 'com.example.flutterHolamundo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjSFZ5yp9K-vHOmsFKZ-SwJrYMJD70e3U',
    appId: '1:172786211960:ios:45687f8d8cd54d7fd3618d',
    messagingSenderId: '172786211960',
    projectId: 'flutter-pokedex-b1b6c',
    storageBucket: 'flutter-pokedex-b1b6c.firebasestorage.app',
    iosBundleId: 'com.example.flutterHolamundo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZ8kPJ8VcGUkJhEkr5iFAjoePNlaQv8E',
    appId: '1:172786211960:web:921a659840f19134d3618d',
    messagingSenderId: '172786211960',
    projectId: 'flutter-pokedex-b1b6c',
    authDomain: 'flutter-pokedex-b1b6c.firebaseapp.com',
    storageBucket: 'flutter-pokedex-b1b6c.firebasestorage.app',
  );
}
